In [1]:
# 1. Check packages
packages <- c(
  "spanishoddata",
  "dplyr",
  "sf",
  "arrow"
)

sapply(
  packages,
  requireNamespace,
  quietly = TRUE
)

spanishoddata         dplyr            sf         arrow
        FALSE          TRUE          TRUE          TRUE

In [4]:
r_lib <- "/projappl/project_2010417/project_rpackages_452"

dir.create(
  r_lib,
  recursive = TRUE,
  showWarnings = FALSE
)

.libPaths(
  c(
    r_lib,
    .libPaths()
  )
)

.libPaths()

[1] "/projappl/project_2010417/project_rpackages_452"
[2] "/usr/lib64/R/library"
[3] "/appl/soft/manual/aida/x86_64/r-env/452/452-rpackages"

In [5]:
install.packages(
  "spanishoddata",
  lib = "/projappl/project_2010417/project_rpackages_452",
  repos = c(
    "https://ropenspain.r-universe.dev",
    "https://cloud.r-project.org"
  )
)

In [6]:
library(spanishoddata)

packageVersion("spanishoddata")

[1] ‘0.2.6.9000’

In [7]:
sapply(
  c(
    "spanishoddata",
    "dplyr",
    "sf",
    "arrow",
    "duckdb",
    "DBI"
  ),
  requireNamespace,
  quietly = TRUE
)

spanishoddata         dplyr            sf         arrow        duckdb
         TRUE          TRUE          TRUE          TRUE          TRUE
          DBI
         TRUE

In [8]:
library(spanishoddata)
library(dplyr)
library(sf)

project_root <- paste0(
  "/scratch/project_2010417/paper3/",
  "heat-conditioned-accessibility"
)

mobile_raw <- file.path(
  project_root,
  "data/mobile/raw"
)

mobile_interim <- file.path(
  project_root,
  "data/mobile/interim"
)

dir.create(
  mobile_raw,
  recursive = TRUE,
  showWarnings = FALSE
)

dir.create(
  mobile_interim,
  recursive = TRUE,
  showWarnings = FALSE
)

spod_set_data_dir(mobile_raw)

spod_get_data_dir()

Attaching package: ‘dplyr’


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union


Linking to GEOS 3.14.1, GDAL 3.12.0, PROJ 9.7.1; sf_use_s2() is TRUE

Data directory is writeable.

Data directory successfully set to: /scratch/project_2010417/paper3/heat-conditioned-accessibility/data/mobile/raw

/scratch/project_2010417/paper3/heat-conditioned-accessibility/data/mobile/raw

In [9]:
districts <- spod_get_zones(
  zones = "districts",
  ver = 2
)

names(districts)

Fetching latest metadata from AmazonS3 (v2)...

S3 fetch failed (MissingRegion (HTTP NA). missing region); falling back to XML sequence.

Fetching latest data links xml

Saving the file to: /scratch/project_2010417/paper3/heat-conditioned-accessibility/data/mobile/raw/metadata_cache/data_links_v2_2026-10-15.xml

Downloading missing zones data...

Deleting source `/scratch/project_2010417/paper3/heat-conditioned-accessibility/data/mobile/raw/clean_data/v2/zones/distritos_mitma.gpkg' failed
Writing layer `distritos_mitma' to data source
  `/scratch/project_2010417/paper3/heat-conditioned-accessibility/data/mobile/raw/clean_data/v2/zones/distritos_mitma.gpkg' using driver `GPKG'
Writing 3909 features with 9 fields and geometry type Unknown (any).

 [1] "id"                   "name"                 "population"
 [4] "census_sections"      "census_districts"     "municipalities"
 [7] "municipalities_mitma" "luas_mitma"           "district_ids_in_v1"
[10] "geometry"

In [10]:
sevilla_candidates <- districts |>
  filter(
    grepl(
      "Sevilla",
      name,
      ignore.case = TRUE
    )
  )

sevilla_candidates

Registered S3 method overwritten by 'geojsonsf':
  method        from
  print.geojson geojson

   id      name                  population
1  28141   Sevilla la Nueva        9345
2  4109101 Sevilla distrito 01    54914
3  4109102 Sevilla distrito 02    73367
4  4109103 Sevilla distrito 03    50394
5  4109104 Sevilla distrito 04    88244
6  4109105 Sevilla distrito 05    68916
7  4109106 Sevilla distrito 06    46253
8  4109107 Sevilla distrito 07    72030
9  4109108 Sevilla distrito 08    59239
10 4109109 Sevilla distrito 09   104255
11 4109110 Sevilla distrito 10    41589
12 4109111 Sevilla distrito 11    25033
13 41903   Cuervo de Sevilla, El   8667
   census_sections
1  2814101001; 2814101002; 2814101003; 2814101004
2  4109101001; 4109101002; 4109101003; 4109101004; 4109101005; 4109101006; 4109101007; 4109101008; 4109101009; 4109101010; 4109101011; 4109101012; 4109101013; 4109101014; 4109101016; 4109101017; 4109101018; 4109101019; 4109101020; 4109101021; 4109101022; 4109101023; 4109101024; 4109101025; 4109101026; 4109101027; 4109101028; 4109101029; 4109101030; 4109101032; 4109101033; 4109101034; 4109101035; 4109101037; 4109101038; 4109101039; 4109101040; 4109101041; 4109101042; 4109101043; 4109101045; 4109101046; 4109101047; 4109101048; 4109101049; 4109101050; 4109101051
3  4109102001; 4109102002; 4109102003; 4109102004; 4109102005; 4109102006; 4109102007; 4109102008; 4109102009; 4109102010; 4109102011; 4109102012; 4109102013; 4109102014; 4109102015; 4109102016; 4109102017; 4109102018; 4109102019; 4109102020; 4109102021; 4109102022; 4109102023; 4109102024; 4109102025; 4109102026; 4109102027; 4109102028; 4109102029; 4109102030; 4109102031; 4109102032; 4109102033; 4109102036; 4109102038; 4109102039; 4109102040; 4109102041; 4109102042; 4109102043; 4109102044; 4109102045; 4109102047; 4109102048; 4109102049; 4109102050; 4109102051; 4109102052; 4109102053; 4109102054; 4109102055; 4109102056; 4109102057; 4109102058; 4109102060; 4109102061; 4109102063; 4109102064; 4109102065; 4109102066; 4109102067
4  4109103001; 4109103002; 4109103003; 4109103004; 4109103005; 4109103006; 4109103007; 4109103008; 4109103009; 4109103010; 4109103011; 4109103012; 4109103013; 4109103014; 4109103015; 4109103016; 4109103017; 4109103019; 4109103020; 4109103021; 4109103022; 4109103023; 4109103024; 4109103025; 4109103026; 4109103027; 4109103028; 4109103029; 4109103030; 4109103031; 4109103032; 4109103033; 4109103034; 4109103035; 4109103036; 4109103037; 4109103038; 4109103039; 4109103040; 4109103041; 4109103042
5  4109104001; 4109104002; 4109104003; 4109104004; 4109104005; 4109104006; 4109104007; 4109104008; 4109104009; 4109104010; 4109104011; 4109104012; 4109104013; 4109104014; 4109104015; 4109104016; 4109104017; 4109104018; 4109104019; 4109104020; 4109104021; 4109104022; 4109104023; 4109104024; 4109104025; 4109104026; 4109104027; 4109104028; 4109104029; 4109104030; 4109104031; 4109104032; 4109104033; 4109104034; 4109104035; 4109104036; 4109104037; 4109104038; 4109104039; 4109104040; 4109104041; 4109104042; 4109104043; 4109104044; 4109104045; 4109104046; 4109104047; 4109104048; 4109104049; 4109104050; 4109104052; 4109104053; 4109104054; 4109104055; 4109104056; 4109104057; 4109104058; 4109104059; 4109104060; 4109104061; 4109104062; 4109104063; 4109104064; 4109104065; 4109104066; 4109104067; 4109104068; 4109104069; 4109104070
6  4109105001; 4109105002; 4109105003; 4109105004; 4109105005; 4109105006; 4109105007; 4109105008; 4109105009; 4109105010; 4109105011; 4109105012; 4109105013; 4109105014; 4109105015; 4109105016; 4109105017; 4109105018; 4109105019; 4109105020; 4109105021; 4109105022; 4109105023; 4109105024; 4109105025; 4109105027; 4109105029; 4109105030; 4109105031; 4109105032; 4109105033; 4109105034; 4109105035; 4109105036; 4109105037; 4109105038; 4109105039; 4109105040; 4109105041; 4109105042; 4109105043; 4109105044; 4109105045; 4109105046; 4109105047; 4109105048; 4109105049; 4109105050; 4109105051; 4109105052; 4109105054; 4109105056; 4109105057
7  4109106001; 4109106002; 4109106003; 4109106004; 4109106005; 4109106006; 4109106007; 4109106008; 4109106009; 4109106010; 4109106011; 4109106012; 4109106013; 4109106014; 4109106015; 4109106016; 4109106017; 4109106018; 4109106019; 4109106020; 4109106021; 4109106022; 4109106023; 4109106024; 4109106025; 4109106026; 4109106027; 4109106028; 4109106029; 4109106030; 4109106031; 4109106032; 4109106033; 4109106034; 4109106035; 4109106036; 4109106037; 4109106038; 4109106039; 4109106040; 4109106041; 4109106042; 4109106043
8  4109107001; 4109107002; 4109107003; 4109107004; 4109107005; 4109107006; 4109107007; 4109107008; 4109107009; 4109107010; 4109107011; 4109107012; 4109107013; 4109107014; 4109107015; 4109107016; 4109107017; 4109107018; 4109107019; 4109107020; 4109107021; 4109107022; 4109107023; 4109107024; 4109107025; 4109107026; 4109107027; 4109107028; 4109107029; 4109107030; 4109107031; 4109107032; 4109107033; 4109107034; 4109107035; 4109107036; 4109107037; 4109107038; 4109107039; 4109107040; 4109107041; 4109107042; 4109107043; 4109107044; 4109107045; 4109107046; 4109107047; 4109107048; 4109107049; 4109107050; 4109107051
9  4109108001; 4109108002; 4109108003; 4109108004; 4109108005; 4109108006; 4109108007; 4109108008; 4109108009; 4109108010; 4109108011; 4109108012; 4109108013; 4109108014; 4109108015; 4109108016; 4109108017; 4109108018; 4109108019; 4109108020; 4109108021; 4109108022; 4109108023; 4109108024; 4109108025; 4109108026; 4109108027; 4109108028; 4109108029; 4109108030; 4109108031; 4109108032; 4109108033; 4109108034; 4109108035; 4109108036; 4109108037; 4109108038; 4109108039; 4109108041; 4109108042; 4109108043; 4109108045; 4109108046; 4109108047; 4109108048; 4109108049; 4109108050; 4109108051; 4109108052
10 4109109001; 4109109002; 4109109003; 4109109004; 4109109005; 4109109006; 4109109007; 4109109008; 4109109009; 4109109010; 4109109011; 4109109012; 4109109013; 4109109014; 4109109015; 4109109016; 4109109017; 4109109018; 4109109019; 4109109020; 4109109021; 4109109022; 4109109023; 4109109024; 4109109025; 4109109026; 4109109027; 4109109028; 4109109029; 4109109030; 4109109031; 4109109032; 4109109033; 4109109034; 4109109035; 4109109036; 4109109037; 4109109039; 4109109040; 4109109041; 4109109042; 4109109043; 4109109044; 4109109045; 4109109046; 4109109047; 4109109048; 4109109049; 4109109050; 4109109051; 4109109052; 4109109053; 4109109054; 4109109055; 4109109056; 4109109057; 4109109058; 4109109059; 4109109060; 4109109061; 4109109062; 4109109063; 4109109064; 4109109065; 4109109066; 4109109067; 4109109068; 4109109069; 4109109070
11 4109110001; 4109110002; 4109110003; 4109110004; 4109110005; 4109110006; 4109110007; 4109110008; 4109110009; 4109110010; 4109110011; 4109110012; 4109110013; 4109110014; 4109110015; 4109110016; 4109110017; 4109110018; 4109110019; 4109110020; 4109110021; 4109110022; 4109110023; 4109110024; 4109110025; 4109110026; 4109110027; 4109110028; 4109110029
12 4109111001; 4109111002; 4109111003; 4109111004; 4109111005; 4109111006; 4109111007; 4109111008; 4109111009; 4109111010; 4109111011; 4109111012; 4109111013; 4109111014; 4109111015; 4109111016; 4109111017; 4109111018; 4109111019
13 4190301001; 4190301002; 4190301003; 4190301004; 4190301005
   census_districts municipalities municipalities_mitma luas_mitma
1  2814101          28141          28141                GAU Madrid
2  4109101          41091          41091                GAU Sevilla
3  4109102          41091          41091                GAU Sevilla
4  4109103          41091          41091                GAU Sevilla
5  4109104          41091          41091                GAU Sevilla
6  4109105          41091          41091                GAU Sevilla
7  4109106          41091          41091                GAU Sevilla
8  4109107          41091          41091                GAU Sevilla
9  4109108          41091          41091                GAU Sevilla
10 4109109          41091          41091                GAU Sevilla
11 4109110          41091          41091                GAU Sevilla
12 4109111          41091          41091                GAU Sevilla
13 4190301          41903          41903                41903
   district_ids_in_v1 geometry
1  28141              MULTIPOLYGON (((415152.1 44...
2  4109101            MULTIPOLYGON (((234784.1 41...
3  4109102            MULTIPOLYGON (((237223.7 41...
4  4109103            MULTIPOLYGON (((237808.3 41...
5  4109104            MULTIPOLYGON (((239896.1 41...
6  4109105            MULTIPOLYGON (((236429.5 41...
7  4109106            MULTIPOLYGON (((233791 4140...
8  4109107            MULTIPOLYGON (((237340.2 41...
9  4109108            MULTIPOLYGON (((236277.3 41...
10 4109109            MULTIPOLYGON (((241920.1 41...
11 4109110            MULTIPOLYGON (((237169.2 41...
12 4109111            MULTIPOLYGON (((231177.6 41...
13 41903              MULTIPOLYGON (((229368.3 40...

In [11]:
st_write(
  districts,
  file.path(
    mobile_interim,
    "spain_districts_v2.gpkg"
  ),
  delete_dsn = TRUE
)

Deleting source `/scratch/project_2010417/paper3/heat-conditioned-accessibility/data/mobile/interim/spain_districts_v2.gpkg' failed
Writing layer `spain_districts_v2' to data source
  `/scratch/project_2010417/paper3/heat-conditioned-accessibility/data/mobile/interim/spain_districts_v2.gpkg' using driver `GPKG'
Writing 3909 features with 9 fields and geometry type Unknown (any).

In [12]:
names(districts)

 [1] "id"                   "name"                 "population"
 [4] "census_sections"      "census_districts"     "municipalities"
 [7] "municipalities_mitma" "luas_mitma"           "district_ids_in_v1"
[10] "geometry"

In [13]:
sevilla_candidates

   id      name                  population
1  28141   Sevilla la Nueva        9345
2  4109101 Sevilla distrito 01    54914
3  4109102 Sevilla distrito 02    73367
4  4109103 Sevilla distrito 03    50394
5  4109104 Sevilla distrito 04    88244
6  4109105 Sevilla distrito 05    68916
7  4109106 Sevilla distrito 06    46253
8  4109107 Sevilla distrito 07    72030
9  4109108 Sevilla distrito 08    59239
10 4109109 Sevilla distrito 09   104255
11 4109110 Sevilla distrito 10    41589
12 4109111 Sevilla distrito 11    25033
13 41903   Cuervo de Sevilla, El   8667
   census_sections
1  2814101001; 2814101002; 2814101003; 2814101004
2  4109101001; 4109101002; 4109101003; 4109101004; 4109101005; 4109101006; 4109101007; 4109101008; 4109101009; 4109101010; 4109101011; 4109101012; 4109101013; 4109101014; 4109101016; 4109101017; 4109101018; 4109101019; 4109101020; 4109101021; 4109101022; 4109101023; 4109101024; 4109101025; 4109101026; 4109101027; 4109101028; 4109101029; 4109101030; 4109101032; 4109101033; 4109101034; 4109101035; 4109101037; 4109101038; 4109101039; 4109101040; 4109101041; 4109101042; 4109101043; 4109101045; 4109101046; 4109101047; 4109101048; 4109101049; 4109101050; 4109101051
3  4109102001; 4109102002; 4109102003; 4109102004; 4109102005; 4109102006; 4109102007; 4109102008; 4109102009; 4109102010; 4109102011; 4109102012; 4109102013; 4109102014; 4109102015; 4109102016; 4109102017; 4109102018; 4109102019; 4109102020; 4109102021; 4109102022; 4109102023; 4109102024; 4109102025; 4109102026; 4109102027; 4109102028; 4109102029; 4109102030; 4109102031; 4109102032; 4109102033; 4109102036; 4109102038; 4109102039; 4109102040; 4109102041; 4109102042; 4109102043; 4109102044; 4109102045; 4109102047; 4109102048; 4109102049; 4109102050; 4109102051; 4109102052; 4109102053; 4109102054; 4109102055; 4109102056; 4109102057; 4109102058; 4109102060; 4109102061; 4109102063; 4109102064; 4109102065; 4109102066; 4109102067
4  4109103001; 4109103002; 4109103003; 4109103004; 4109103005; 4109103006; 4109103007; 4109103008; 4109103009; 4109103010; 4109103011; 4109103012; 4109103013; 4109103014; 4109103015; 4109103016; 4109103017; 4109103019; 4109103020; 4109103021; 4109103022; 4109103023; 4109103024; 4109103025; 4109103026; 4109103027; 4109103028; 4109103029; 4109103030; 4109103031; 4109103032; 4109103033; 4109103034; 4109103035; 4109103036; 4109103037; 4109103038; 4109103039; 4109103040; 4109103041; 4109103042
5  4109104001; 4109104002; 4109104003; 4109104004; 4109104005; 4109104006; 4109104007; 4109104008; 4109104009; 4109104010; 4109104011; 4109104012; 4109104013; 4109104014; 4109104015; 4109104016; 4109104017; 4109104018; 4109104019; 4109104020; 4109104021; 4109104022; 4109104023; 4109104024; 4109104025; 4109104026; 4109104027; 4109104028; 4109104029; 4109104030; 4109104031; 4109104032; 4109104033; 4109104034; 4109104035; 4109104036; 4109104037; 4109104038; 4109104039; 4109104040; 4109104041; 4109104042; 4109104043; 4109104044; 4109104045; 4109104046; 4109104047; 4109104048; 4109104049; 4109104050; 4109104052; 4109104053; 4109104054; 4109104055; 4109104056; 4109104057; 4109104058; 4109104059; 4109104060; 4109104061; 4109104062; 4109104063; 4109104064; 4109104065; 4109104066; 4109104067; 4109104068; 4109104069; 4109104070
6  4109105001; 4109105002; 4109105003; 4109105004; 4109105005; 4109105006; 4109105007; 4109105008; 4109105009; 4109105010; 4109105011; 4109105012; 4109105013; 4109105014; 4109105015; 4109105016; 4109105017; 4109105018; 4109105019; 4109105020; 4109105021; 4109105022; 4109105023; 4109105024; 4109105025; 4109105027; 4109105029; 4109105030; 4109105031; 4109105032; 4109105033; 4109105034; 4109105035; 4109105036; 4109105037; 4109105038; 4109105039; 4109105040; 4109105041; 4109105042; 4109105043; 4109105044; 4109105045; 4109105046; 4109105047; 4109105048; 4109105049; 4109105050; 4109105051; 4109105052; 4109105054; 4109105056; 4109105057
7  4109106001; 4109106002; 4109106003; 4109106004; 4109106005; 4109106006; 4109106007; 4109106008; 4109106009; 4109106010; 4109106011; 4109106012; 4109106013; 4109106014; 4109106015; 4109106016; 4109106017; 4109106018; 4109106019; 4109106020; 4109106021; 4109106022; 4109106023; 4109106024; 4109106025; 4109106026; 4109106027; 4109106028; 4109106029; 4109106030; 4109106031; 4109106032; 4109106033; 4109106034; 4109106035; 4109106036; 4109106037; 4109106038; 4109106039; 4109106040; 4109106041; 4109106042; 4109106043
8  4109107001; 4109107002; 4109107003; 4109107004; 4109107005; 4109107006; 4109107007; 4109107008; 4109107009; 4109107010; 4109107011; 4109107012; 4109107013; 4109107014; 4109107015; 4109107016; 4109107017; 4109107018; 4109107019; 4109107020; 4109107021; 4109107022; 4109107023; 4109107024; 4109107025; 4109107026; 4109107027; 4109107028; 4109107029; 4109107030; 4109107031; 4109107032; 4109107033; 4109107034; 4109107035; 4109107036; 4109107037; 4109107038; 4109107039; 4109107040; 4109107041; 4109107042; 4109107043; 4109107044; 4109107045; 4109107046; 4109107047; 4109107048; 4109107049; 4109107050; 4109107051
9  4109108001; 4109108002; 4109108003; 4109108004; 4109108005; 4109108006; 4109108007; 4109108008; 4109108009; 4109108010; 4109108011; 4109108012; 4109108013; 4109108014; 4109108015; 4109108016; 4109108017; 4109108018; 4109108019; 4109108020; 4109108021; 4109108022; 4109108023; 4109108024; 4109108025; 4109108026; 4109108027; 4109108028; 4109108029; 4109108030; 4109108031; 4109108032; 4109108033; 4109108034; 4109108035; 4109108036; 4109108037; 4109108038; 4109108039; 4109108041; 4109108042; 4109108043; 4109108045; 4109108046; 4109108047; 4109108048; 4109108049; 4109108050; 4109108051; 4109108052
10 4109109001; 4109109002; 4109109003; 4109109004; 4109109005; 4109109006; 4109109007; 4109109008; 4109109009; 4109109010; 4109109011; 4109109012; 4109109013; 4109109014; 4109109015; 4109109016; 4109109017; 4109109018; 4109109019; 4109109020; 4109109021; 4109109022; 4109109023; 4109109024; 4109109025; 4109109026; 4109109027; 4109109028; 4109109029; 4109109030; 4109109031; 4109109032; 4109109033; 4109109034; 4109109035; 4109109036; 4109109037; 4109109039; 4109109040; 4109109041; 4109109042; 4109109043; 4109109044; 4109109045; 4109109046; 4109109047; 4109109048; 4109109049; 4109109050; 4109109051; 4109109052; 4109109053; 4109109054; 4109109055; 4109109056; 4109109057; 4109109058; 4109109059; 4109109060; 4109109061; 4109109062; 4109109063; 4109109064; 4109109065; 4109109066; 4109109067; 4109109068; 4109109069; 4109109070
11 4109110001; 4109110002; 4109110003; 4109110004; 4109110005; 4109110006; 4109110007; 4109110008; 4109110009; 4109110010; 4109110011; 4109110012; 4109110013; 4109110014; 4109110015; 4109110016; 4109110017; 4109110018; 4109110019; 4109110020; 4109110021; 4109110022; 4109110023; 4109110024; 4109110025; 4109110026; 4109110027; 4109110028; 4109110029
12 4109111001; 4109111002; 4109111003; 4109111004; 4109111005; 4109111006; 4109111007; 4109111008; 4109111009; 4109111010; 4109111011; 4109111012; 4109111013; 4109111014; 4109111015; 4109111016; 4109111017; 4109111018; 4109111019
13 4190301001; 4190301002; 4190301003; 4190301004; 4190301005
   census_districts municipalities municipalities_mitma luas_mitma
1  2814101          28141          28141                GAU Madrid
2  4109101          41091          41091                GAU Sevilla
3  4109102          41091          41091                GAU Sevilla
4  4109103          41091          41091                GAU Sevilla
5  4109104          41091          41091                GAU Sevilla
6  4109105          41091          41091                GAU Sevilla
7  4109106          41091          41091                GAU Sevilla
8  4109107          41091          41091                GAU Sevilla
9  4109108          41091          41091                GAU Sevilla
10 4109109          41091          41091                GAU Sevilla
11 4109110          41091          41091                GAU Sevilla
12 4109111          41091          41091                GAU Sevilla
13 4190301          41903          41903                41903
   district_ids_in_v1 geometry
1  28141              MULTIPOLYGON (((415152.1 44...
2  4109101            MULTIPOLYGON (((234784.1 41...
3  4109102            MULTIPOLYGON (((237223.7 41...
4  4109103            MULTIPOLYGON (((237808.3 41...
5  4109104            MULTIPOLYGON (((239896.1 41...
6  4109105            MULTIPOLYGON (((236429.5 41...
7  4109106            MULTIPOLYGON (((233791 4140...
8  4109107            MULTIPOLYGON (((237340.2 41...
9  4109108            MULTIPOLYGON (((236277.3 41...
10 4109109            MULTIPOLYGON (((241920.1 41...
11 4109110            MULTIPOLYGON (((237169.2 41...
12 4109111            MULTIPOLYGON (((231177.6 41...
13 41903              MULTIPOLYGON (((229368.3 40...

In [14]:
sevilla_zones <- districts |>
  filter(municipalities == "41091")

sevilla_zones |>
  select(
    id,
    name,
    population,
    municipalities,
    luas_mitma
  )

   id      name                population municipalities luas_mitma
1  4109101 Sevilla distrito 01  54914     41091          GAU Sevilla
2  4109102 Sevilla distrito 02  73367     41091          GAU Sevilla
3  4109103 Sevilla distrito 03  50394     41091          GAU Sevilla
4  4109104 Sevilla distrito 04  88244     41091          GAU Sevilla
5  4109105 Sevilla distrito 05  68916     41091          GAU Sevilla
6  4109106 Sevilla distrito 06  46253     41091          GAU Sevilla
7  4109107 Sevilla distrito 07  72030     41091          GAU Sevilla
8  4109108 Sevilla distrito 08  59239     41091          GAU Sevilla
9  4109109 Sevilla distrito 09 104255     41091          GAU Sevilla
10 4109110 Sevilla distrito 10  41589     41091          GAU Sevilla
11 4109111 Sevilla distrito 11  25033     41091          GAU Sevilla
   geometry
1  MULTIPOLYGON (((234784.1 41...
2  MULTIPOLYGON (((237223.7 41...
3  MULTIPOLYGON (((237808.3 41...
4  MULTIPOLYGON (((239896.1 41...
5  MULTIPOLYGON (((236429.5 41...
6  MULTIPOLYGON (((233791 4140...
7  MULTIPOLYGON (((237340.2 41...
8  MULTIPOLYGON (((236277.3 41...
9  MULTIPOLYGON (((241920.1 41...
10 MULTIPOLYGON (((237169.2 41...
11 MULTIPOLYGON (((231177.6 41...

In [15]:
st_write(
  sevilla_zones,
  file.path(
    mobile_interim,
    "sevilla_districts_v2.gpkg"
  ),
  delete_dsn = TRUE
)

Deleting source `/scratch/project_2010417/paper3/heat-conditioned-accessibility/data/mobile/interim/sevilla_districts_v2.gpkg' failed
Writing layer `sevilla_districts_v2' to data source
  `/scratch/project_2010417/paper3/heat-conditioned-accessibility/data/mobile/interim/sevilla_districts_v2.gpkg' using driver `GPKG'
Writing 11 features with 9 fields and geometry type Multi Polygon.

In [16]:
sevilla_ids <- sevilla_zones$id

sevilla_ids

 [1] "4109101" "4109102" "4109103" "4109104" "4109105" "4109106" "4109107"
 [8] "4109108" "4109109" "4109110" "4109111"

In [17]:
test_date <- "2024-07-15"

In [18]:
od_test <- spod_get(
  type = "od",
  zones = "districts",
  dates = test_date
)

Data version detected from dates: 2

Fetching latest metadata from AmazonS3 (v2)...

S3 fetch failed (MissingRegion (HTTP NA). missing region); falling back to XML sequence.

Downloading approximately 0.21 GB of data.

Retrieved data for requested dates.

duckdb keeps downloaded extensions and secrets in a temporary directory:
ℹ /tmp/modjrian/2332740/RtmpSbxee4/duckdb
This is removed when the R session ends.
• Extensions are re-downloaded each session.
• Secrets are lost.
ℹ Run duckdb(shared_home = TRUE) (or create ~/.duckdb) to keep them (suitable for most users).
ℹ Run duckdb(shared_home = FALSE) to accept the temporary directory (and silence this message).
ℹ See ?duckdb_storage for details and alternatives.

In [19]:
class(od_test)

names(od_test)

[1] "tbl_duckdb_connection" "tbl_dbi"               "tbl_sql"
[4] "tbl_lazy"              "tbl"

! The `names()` method of <tbl_lazy> is for internal use only.
ℹ Did you mean `colnames()`?

[1] "src"        "lazy_query"

In [20]:
sevilla_od_test <- od_test |>
  filter(
    id_origin %in% sevilla_ids |
    id_destination %in% sevilla_ids
  )

In [21]:
sevilla_od_test |>
  head()

# Source:   SQL [?? x 19]
# Database: DuckDB 1.5.5 [unknown@Linux 5.14.0-687.54.1.el9_8.x86_64:R 4.5.2/:memory:]
  date        hour id_origin id_destination distance activity_origin
  <date>     <int> <fct>     <fct>          <fct>    <fct>
1 2024-07-15     0 4109101   41003          10-50    frequent_activity
2 2024-07-15     7 4109101   41003          10-50    frequent_activity
3 2024-07-15    11 4109101   41003          10-50    frequent_activity
4 2024-07-15    13 4109101   41003          10-50    frequent_activity
5 2024-07-15    15 4109101   41003          10-50    frequent_activity
6 2024-07-15    16 4109101   41003          10-50    frequent_activity
# ℹ 13 more variables: activity_destination <fct>, study_possible_origin <lgl>,
#   study_possible_destination <lgl>, residence_province_ine_code <fct>,
#   residence_province_name <fct>, income <fct>, age <fct>, sex <fct>,
#   n_trips <dbl>, trips_total_length_km <dbl>, year <int>, month <int>,
#   day <int>

In [22]:
sevilla_od_test <- sevilla_od_test |>
  collect()

dim(sevilla_od_test)

names(sevilla_od_test)

head(sevilla_od_test)

[1] 395076     19

 [1] "date"                        "hour"
 [3] "id_origin"                   "id_destination"
 [5] "distance"                    "activity_origin"
 [7] "activity_destination"        "study_possible_origin"
 [9] "study_possible_destination"  "residence_province_ine_code"
[11] "residence_province_name"     "income"
[13] "age"                         "sex"
[15] "n_trips"                     "trips_total_length_km"
[17] "year"                        "month"
[19] "day"

  date       hour id_origin id_destination distance activity_origin
1 2024-07-15 20   4109101   14042          >50      infrequent_activity
2 2024-07-15 12   4109107   14042          >50      infrequent_activity
3 2024-07-15 19   4109108   14042          >50      infrequent_activity
4 2024-07-15 11   4109110   14042          >50      infrequent_activity
5 2024-07-15 20   4109101   14042          >50      infrequent_activity
6 2024-07-15 16   4109105   14042          >50      infrequent_activity
  activity_destination study_possible_origin study_possible_destination
1 home                 FALSE                 FALSE
2 home                 FALSE                 FALSE
3 home                 FALSE                 FALSE
4 home                 FALSE                 FALSE
5 home                 FALSE                 FALSE
6 home                 FALSE                 FALSE
  residence_province_ine_code residence_province_name income age   sex
1 14                          Córdoba                 10-15  0-25  male
2 14                          Córdoba                 10-15  0-25  male
3 14                          Córdoba                 10-15  0-25  female
4 14                          Córdoba                 <10    0-25  male
5 14                          Córdoba                 <10    25-45 female
6 14                          Córdoba                 10-15  25-45 male
  n_trips trips_total_length_km year month day
1 12.809  1553.645              2024 7     15
2  3.839   437.507              2024 7     15
3  3.619   409.645              2024 7     15
4  2.691   332.873              2024 7     15
5  2.236   272.796              2024 7     15
6  2.684   328.295              2024 7     15

In [23]:
arrow::write_parquet(
  sevilla_od_test,
  file.path(
    mobile_interim,
    "sevilla_od_2024-07-15.parquet"
  )
)

In [24]:
names(od_test)

! The `names()` method of <tbl_lazy> is for internal use only.
ℹ Did you mean `colnames()`?

[1] "src"        "lazy_query"